import os
import time

category = raw_input("Enter the target Category name: ")
print('Category: {}\n'.format(category))
category = category.capitalize()
with open("category.txt",'w') as f:
    f.write(category)

start = time.time()
print('Retrieving DMOZ Websites...\n')
os.system('python sample.py')
print('Output: <seeds.txt>\n')
print('Crawling keywords from Alexa...')
os.system('python keywords.py')
print('Output: <keywords.txt>\n')
print('Summarizing keywords...')
os.system('python readjson.py')
print('Output: <topkeywords.txt>\n')
print('Debugging Output: <keywordsrank.txt>\n')
print('Searching from Bing...')
os.system('python bingquery.py')
print('Output: <bingresults.txt>\n')
print('Analyzing Bing Search results...')
os.system('python processbingresult.py')
print('Output: <processedresults.txt>\n')
print('Debugging Output: <processedfullresults.txt>\n')
print('Excluding Alexa ranked sites...')
os.system('python batchalexarank.py')
print('Output: <filterresult.txt>\n')
print('Performing Blacklist Check...')
os.system('python dig_BL.py')
print('Output: <Blacklist_Check_Score.txt>\n')
print('Retrieving Social Reputation by Site...')
os.system('python socialrep.py')
print('Processing Results...\n')
print('Final Output: <social_rank_search.txt>\n')
print('Cleaning up...')
os.system('mkdir '+category)
os.system('mv *.txt '+category+'/')
os.system('cp 3d_plot.py '+category+'/')
os.system('python -W ignore '+category+'/3d_plot.py')


end = time.time()
print('Instructions Completed in ')
print(end - start)
print('seconds.\n')